### PR TITLE
Added pathway figures to index from the EpiLipidNET #lipidhack23 hackathon

### PR DESCRIPTION
**Pull request by egonw**
In draft right now. More figures will follow.

### CODE REVIEW

**Comment by egonw** [comment]
Actually, there are some other things I want to do this afternoon, so will add pathway figures from other articles at some later point. So, ready to be merged into the pipeline :)

**Comment by egonw** [comment]
@AlexanderPico, what happened to this file? it seems to have gone lost? 

image

**Comment by egonw** [comment]
Okay, with some more digging, it seems it got removed in https://github.com/wikipathways/pfocr-pmcfigurebot/commit/7d3d3dca2da0140f9c81b05506a0ba26979fb500

**Comment by AlexanderPico** [comment]
Confirmed that this figure was collected and is in queue for processing in the 20240701 batch.

**Comment by AlexanderPico** [comment]
Was not recognized as a pathway by ML step in pipeline :(

Will have to figure out how to force it next time...

**Comment by AlexanderPico** [comment]
Fixed!
* https://pfocr.wikipathways.org/figures/PMC4631354__pone.0141850.g003

**Pull request merged**
